// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW22eb7qH72hzSdyeJr_E0kX9Gb0R8QiM',
    appId: '1:1051292249137:web:4d12ab4df1ac146b677910',
    messagingSenderId: '1051292249137',
    projectId: 'bridgecall-ai',
    authDomain: 'bridgecall-ai.firebaseapp.com',
    storageBucket: 'bridgecall-ai.firebasestorage.app',
    measurementId: 'G-Q97718GD50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAftGfEMQDbsNHTipTs_51msEX1-oyTk0o',
    appId: '1:1051292249137:android:24b57324082c69c7677910',
    messagingSenderId: '1051292249137',
    projectId: 'bridgecall-ai',
    storageBucket: 'bridgecall-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-SVHUFsN3tHZcvaQYzDWjLKwL8ZXz2g',
    appId: '1:1051292249137:ios:e6a45b0635ddb095677910',
    messagingSenderId: '1051292249137',
    projectId: 'bridgecall-ai',
    storageBucket: 'bridgecall-ai.firebasestorage.app',
    iosBundleId: 'com.example.bridgecallAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK-SVHUFsN3tHZcvaQYzDWjLKwL8ZXz2g',
    appId: '1:1051292249137:ios:e6a45b0635ddb095677910',
    messagingSenderId: '1051292249137',
    projectId: 'bridgecall-ai',
    storageBucket: 'bridgecall-ai.firebasestorage.app',
    iosBundleId: 'com.example.bridgecallAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW22eb7qH72hzSdyeJr_E0kX9Gb0R8QiM',
    appId: '1:1051292249137:web:bc5f28ee356b8a6a677910',
    messagingSenderId: '1051292249137',
    projectId: 'bridgecall-ai',
    authDomain: 'bridgecall-ai.firebaseapp.com',
    storageBucket: 'bridgecall-ai.firebasestorage.app',
    measurementId: 'G-G9VGT8PPB8',
  );
}
